# Generated by Django 3.0.5 on 2020-04-29 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 29, 12, 36, 30, 951881), verbose_name='Дата публикации'),
        ),
    ]
