# Generated by Django 3.0.5 on 2020-05-06 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_auto_20200505_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 18, 1, 0, 47906), verbose_name='Дата публикации'),
        ),
    ]
