# Generated by Django 3.0.5 on 2020-05-07 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_auto_20200507_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 12, 5, 26, 514266), verbose_name='Дата публикации'),
        ),
    ]
