# Generated by Django 3.0.6 on 2020-05-14 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_auto_20200514_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 17, 44, 1, 560209), verbose_name='Дата публикации'),
        ),
    ]
