# Generated by Django 3.0.6 on 2020-05-14 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0017_auto_20200514_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 17, 45, 53, 850168), verbose_name='Дата публикации'),
        ),
    ]
