# Generated by Django 3.0.6 on 2020-05-14 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0022_auto_20200514_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 18, 15, 38, 87128), verbose_name='Дата публикации'),
        ),
    ]
