# Generated by Django 3.0.6 on 2020-05-20 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0027_auto_20200520_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 12, 28, 0, 12050), verbose_name='Дата публикации'),
        ),
    ]
